version: '3'

services:
  database:
    container_name: challenge-database
    image: postgres:latest
    restart: no
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ${PG_VOLUME}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  pgadmin:
    container_name: challenge-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
